persistentVolume:
  storageClassName: "local-storage"
  size: "3Gi"
service:
  type: NodePort
  port: 8080
elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
  persistence:
    accessModes: ReadWriteOnce
    size: 5Gi # Adjust the size as per your requirements
    storageClassName: local-storage
postgres:
  persistence:
    accessModes: ReadWriteOnce
    size: 10Gi # Adjust the size as per your requirements
    storageClassName: local-storage
environment:
  POSTGRES_DB: tenjin
  POSTGRES_USER: yethi
  POSTGRES_PASSWORD: Yethi123
  DEFAULT_USER_PASSWORD: Welcome@123
  TENJIN_HOST_NAME: http://localhost
  TENJIN_ALLOWED_URL: http://localhost
