# values.yaml
service:
  port: 8080

elasticsearch:
  config:
    bootstrap_memory_lock: true
    ES_JAVA_OPTS: "-Xms512m -Xmx2G"
    # discovery_type: "single-node"
  # xpack_security_enabled: false
  persistence:
    accessModes: ReadWriteOnce
    size: 5Gi # Adjust the size as per your requirements
    storageClassName: managed-csi

postgres:
  persistence:
    accessModes: ReadWriteOnce
    size: 10Gi # Adjust the size as per your requirements
    storageClassName: managed-csi

# elasticsearch:

persistentVolume:
  enabled: true
  storageClassName: "managed-csi"
  accessModes: ["ReadWriteOnce"]
  size: "3Gi"
