apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: tenjin-es
        image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          limits:
            memory: "4Gi"
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-elasticsearch-config
        command: ["elasticsearch"]
        args: ["-Ehttp.host=0.0.0.0", "-Ediscovery.type=single-node"]
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-pvc
    spec:
      accessModes: [ "{{ .Values.elasticsearch.persistence.accessModes }}" ]
      storageClassName: "{{ .Values.elasticsearch.persistence.storageClassName }}"
      resources:
        requests:
          storage: {{ .Values.elasticsearch.persistence.size }}

---

# PersistentVolume definition for Elasticsearch
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}elasticsearch-pv
spec:
  capacity:
    storage: {{ .Values.elasticsearch.persistence.size  }}
  accessModes:
    - {{ .Values.elasticsearch.persistence.accessModes  }}
  storageClassName: {{ .Values.elasticsearch.persistence.storageClassName }}
  hostPath:
    path: /usr/share/elasticsearch/data