apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: tenjin-db
        image: postgres:13
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-postgres-config
        volumeMounts:
        - name: postgres-pv
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: postgres-pv
    spec:
      accessModes: [ "{{ .Values.postgres.persistence.accessModes | default "ReadWriteOnce" }}" ]
      storageClassName: "{{ .Values.postgres.persistence.storageClassName | default "standard" }}"
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size | default "10Gi" }}


---

# PersistentVolume definition for PostgreSQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: {{ .Values.postgres.persistence.size | default "10Gi" }}  # Example: 10Gi
  accessModes:
    - {{ .Values.postgres.persistence.accessModes | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName | default "standard" }}
  hostPath:
    path: /mnt/postgres