apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin-te4-service
spec:
  selector:
    app: tenjin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: {{ .Values.tenjin.service.type }}