apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tenjin-ai
data:
  HOST: "http://192.168.16.88"
  PORT: "30557"
  OPENAI_API_KEY: "sk-tenjin-enterprise-JDugfTTh2N6jIlnyvmHLT3BlbkFJFQsFzNDznREGzwmHuBRc"
  db_user: "yethi"
  db_password: "Yethi123"
  db_host: "192.168.16.88"
  db_port: "30310"
  db_name: "tenjin"
  db_type: "postgres"
  db_schema: "public"