apiVersion: v1
kind: Service
metadata:
  name: tenjin
  labels:
    app: tenjin
spec:
  type: NodePort  # Moved to spec
  selector:
    app: tenjin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080