apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenjin-te4-service
spec:
  selector:
    app: tenjin-te4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
