apiVersion: v1
kind: Service
metadata:
  name: tenjin
  labels:
    app: tenjin
spec:
  type: {{.Values.tenjin.service.type }}  
  selector:
    app: tenjin
  ports:
    - protocol: TCP
      port: {{.Values.tenjin.service.port }}
      targetPort: 8080